{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "7c7a60c3-52df-41d1-b9a6-59612a672080",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting streamlitNote: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "  Downloading streamlit-1.46.0-py3-none-any.whl.metadata (9.0 kB)\n",
      "Collecting altair<6,>=4.0 (from streamlit)\n",
      "  Downloading altair-5.5.0-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in c:\\python312\\lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<7,>=4.0 in c:\\python312\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\python312\\lib\\site-packages (from streamlit) (8.1.8)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in c:\\python312\\lib\\site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<26,>=20 in c:\\python312\\lib\\site-packages (from streamlit) (24.2)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\python312\\lib\\site-packages (from streamlit) (2.2.3)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in c:\\python312\\lib\\site-packages (from streamlit) (11.1.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in c:\\python312\\lib\\site-packages (from streamlit) (5.28.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\python312\\lib\\site-packages (from streamlit) (19.0.1)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\python312\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Collecting tenacity<10,>=8.1.0 (from streamlit)\n",
      "  Downloading tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\python312\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\\python312\\lib\\site-packages (from streamlit) (4.12.2)\n",
      "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
      "  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)\n",
      "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
      "  Downloading GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)\n",
      "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
      "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\\python312\\lib\\site-packages (from streamlit) (6.4.2)\n",
      "Requirement already satisfied: jinja2 in c:\\python312\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.5)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\python312\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Collecting narwhals>=1.14.2 (from altair<6,>=4.0->streamlit)\n",
      "  Downloading narwhals-1.44.0-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: colorama in c:\\python312\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)\n",
      "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\python312\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\python312\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\python312\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\python312\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\python312\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\python312\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\python312\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\python312\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\python312\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\python312\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\python312\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.1)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\python312\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\python312\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)\n",
      "Downloading streamlit-1.46.0-py3-none-any.whl (10.1 MB)\n",
      "   ---------------------------------------- 0.0/10.1 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/10.1 MB ? eta -:--:--\n",
      "   -- ------------------------------------- 0.5/10.1 MB 1.4 MB/s eta 0:00:07\n",
      "   --- ------------------------------------ 0.8/10.1 MB 1.3 MB/s eta 0:00:07\n",
      "   ----- ---------------------------------- 1.3/10.1 MB 1.8 MB/s eta 0:00:05\n",
      "   ------- -------------------------------- 1.8/10.1 MB 2.0 MB/s eta 0:00:05\n",
      "   --------- ------------------------------ 2.4/10.1 MB 2.1 MB/s eta 0:00:04\n",
      "   ----------- ---------------------------- 2.9/10.1 MB 2.2 MB/s eta 0:00:04\n",
      "   ------------ --------------------------- 3.1/10.1 MB 2.2 MB/s eta 0:00:04\n",
      "   -------------- ------------------------- 3.7/10.1 MB 2.2 MB/s eta 0:00:03\n",
      "   ---------------- ----------------------- 4.2/10.1 MB 2.1 MB/s eta 0:00:03\n",
      "   ------------------ --------------------- 4.7/10.1 MB 2.2 MB/s eta 0:00:03\n",
      "   -------------------- ------------------- 5.2/10.1 MB 2.2 MB/s eta 0:00:03\n",
      "   ---------------------- ----------------- 5.8/10.1 MB 2.2 MB/s eta 0:00:02\n",
      "   ------------------------- -------------- 6.3/10.1 MB 2.3 MB/s eta 0:00:02\n",
      "   --------------------------- ------------ 6.8/10.1 MB 2.3 MB/s eta 0:00:02\n",
      "   ----------------------------- ---------- 7.3/10.1 MB 2.3 MB/s eta 0:00:02\n",
      "   ------------------------------- -------- 7.9/10.1 MB 2.3 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 8.1/10.1 MB 2.4 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 8.7/10.1 MB 2.3 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 9.2/10.1 MB 2.3 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 9.7/10.1 MB 2.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------  10.0/10.1 MB 2.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 10.1/10.1 MB 2.3 MB/s eta 0:00:00\n",
      "Downloading altair-5.5.0-py3-none-any.whl (731 kB)\n",
      "   ---------------------------------------- 0.0/731.2 kB ? eta -:--:--\n",
      "   -------------- ------------------------- 262.1/731.2 kB ? eta -:--:--\n",
      "   ---------------------------------------- 731.2/731.2 kB 2.2 MB/s eta 0:00:00\n",
      "Downloading GitPython-3.1.44-py3-none-any.whl (207 kB)\n",
      "Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)\n",
      "Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
      "   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--\n",
      "   ---- ----------------------------------- 0.8/6.9 MB 4.8 MB/s eta 0:00:02\n",
      "   --------- ------------------------------ 1.6/6.9 MB 4.2 MB/s eta 0:00:02\n",
      "   --------------- ------------------------ 2.6/6.9 MB 4.3 MB/s eta 0:00:01\n",
      "   ------------------- -------------------- 3.4/6.9 MB 4.4 MB/s eta 0:00:01\n",
      "   ------------------------- -------------- 4.5/6.9 MB 4.4 MB/s eta 0:00:01\n",
      "   ------------------------------ --------- 5.2/6.9 MB 4.4 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 6.3/6.9 MB 4.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------  6.8/6.9 MB 4.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 6.9/6.9 MB 4.1 MB/s eta 0:00:00\n",
      "Downloading smmap-5.0.2-py3-none-any.whl (24 kB)\n",
      "Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)\n",
      "Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)\n",
      "Downloading narwhals-1.44.0-py3-none-any.whl (365 kB)\n",
      "Installing collected packages: watchdog, tenacity, smmap, narwhals, pydeck, gitdb, gitpython, altair, streamlit\n",
      "\n",
      "   ---------------------------------------- 0/9 [watchdog]\n",
      "   ---------------------------------------- 0/9 [watchdog]\n",
      "   ---------------------------------------- 0/9 [watchdog]\n",
      "   ---------------------------------------- 0/9 [watchdog]\n",
      "   ---- ----------------------------------- 1/9 [tenacity]\n",
      "   -------- ------------------------------- 2/9 [smmap]\n",
      "   -------- ------------------------------- 2/9 [smmap]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ------------- -------------------------- 3/9 [narwhals]\n",
      "   ----------------- ---------------------- 4/9 [pydeck]\n",
      "   ----------------- ---------------------- 4/9 [pydeck]\n",
      "   ----------------- ---------------------- 4/9 [pydeck]\n",
      "   ----------------- ---------------------- 4/9 [pydeck]\n",
      "   ----------------- ---------------------- 4/9 [pydeck]\n",
      "   ---------------------- ----------------- 5/9 [gitdb]\n",
      "   ---------------------- ----------------- 5/9 [gitdb]\n",
      "   ---------------------- ----------------- 5/9 [gitdb]\n",
      "   -------------------------- ------------- 6/9 [gitpython]\n",
      "   -------------------------- ------------- 6/9 [gitpython]\n",
      "   -------------------------- ------------- 6/9 [gitpython]\n",
      "   -------------------------- ------------- 6/9 [gitpython]\n",
      "   -------------------------- ------------- 6/9 [gitpython]\n",
      "   -------------------------- ------------- 6/9 [gitpython]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ------------------------------- -------- 7/9 [altair]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ----------------------------------- ---- 8/9 [streamlit]\n",
      "   ---------------------------------------- 9/9 [streamlit]\n",
      "\n",
      "Successfully installed altair-5.5.0 gitdb-4.0.12 gitpython-3.1.44 narwhals-1.44.0 pydeck-0.9.1 smmap-5.0.2 streamlit-1.46.0 tenacity-9.1.2 watchdog-6.0.0\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "7e326e56-6e1c-4212-9b25-55d49fbcf521",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import joblib\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "deea4ccd-009f-4d16-855b-787d5cdc20e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = joblib.load('diabetes_model.pkl')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "711d2281-bdcb-42b4-a1ea-225b0ebf07c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-24 20:33:40.640 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "st.set_page_config(\n",
    "    page_title=\"Diabetes Prediction App\",\n",
    "    page_icon=\"🩺\",\n",
    "    layout=\"wide\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "1081e1ed-9333-44e1-81c3-7e00158a5c88",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-24 20:33:42.954 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:33:43.663 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Python312\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-06-24 20:33:43.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:33:43.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    .reportview-container {\n",
    "        background: #f0f2f6\n",
    "    }\n",
    "    .big-font {\n",
    "        font-size:24px !important;\n",
    "        font-weight: bold;\n",
    "    }\n",
    "    .result-box {\n",
    "        padding: 20px;\n",
    "        border-radius: 10px;\n",
    "        margin: 20px 0;\n",
    "        box-shadow: 0 4px 6px rgba(0,0,0,0.1);\n",
    "    }\n",
    "    .diabetic {\n",
    "        background-color: #ffcccc;\n",
    "        border-left: 5px solid #ff4b4b;\n",
    "    }\n",
    "    .non-diabetic {\n",
    "        background-color: #ccffcc;\n",
    "        border-left: 5px solid #4CAF50;\n",
    "    }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "10c9834e-ed66-4101-adb7-0880b7f95e34",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-24 20:33:50.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:33:50.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:33:50.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:33:50.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:33:50.846 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:33:50.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "st.title(\"🩺 Diabetes Prediction App\")\n",
    "st.markdown(\"\"\"\n",
    "This app predicts the likelihood of diabetes using the PIMA Indian Diabetes dataset. \n",
    "The model is trained on diagnostic measurements including glucose levels, BMI, age, and other health indicators.\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "88f513f4-67ae-4703-939f-f7f32484a98b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-24 20:34:05.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:05.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:05.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:05.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:05.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:05.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator(_root_container=1, _parent=DeltaGenerator())"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "st.sidebar.header(\"Patient Parameters\")\n",
    "st.sidebar.markdown(\"Adjust the sliders to input patient health metrics\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "a12cf8b6-5c14-4c84-80bd-6494f2d86d62",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-24 20:34:09.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.139 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.143 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.144 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.155 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.157 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.165 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.172 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.174 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:34:09.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "pregnancies = st.sidebar.slider('Pregnancies', 0, 17, 3)\n",
    "glucose = st.sidebar.slider('Glucose Level (mg/dL)', 0, 200, 120)\n",
    "blood_pressure = st.sidebar.slider('Blood Pressure (mm Hg)', 0, 130, 70)\n",
    "skin_thickness = st.sidebar.slider('Skin Thickness (mm)', 0, 100, 20)\n",
    "insulin = st.sidebar.slider('Insulin Level (mu U/ml)', 0, 850, 80)\n",
    "bmi = st.sidebar.slider('BMI', 0.0, 70.0, 25.0)\n",
    "dpf = st.sidebar.slider('Diabetes Pedigree Function', 0.0, 2.5, 0.35)\n",
    "age = st.sidebar.slider('Age', 20, 90, 30)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "7866babd-7c08-49a8-97a6-061eea6621da",
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict():\n",
    "    input_data = np.array([[\n",
    "        pregnancies, glucose, blood_pressure, \n",
    "        skin_thickness, insulin, bmi, dpf, age\n",
    "    ]])\n",
    "    prediction = model.predict(input_data)[0]\n",
    "    probabilities = model.predict_proba(input_data)[0]\n",
    "    return prediction, probabilities"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "b20ddf58-e2e4-43d0-9b75-418a048b213c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-24 20:41:07.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.887 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.887 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.891 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.906 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.924 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.925 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.936 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:07.938 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:08.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:08.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:08.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:08.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:08.383 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:08.383 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:08.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.155 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.805 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.805 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-24 20:41:09.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "# Main content\n",
    "col1, col2 = st.columns([1, 2])\n",
    "\n",
    "with col1:\n",
    "    st.header(\"Patient Input Summary\")\n",
    "    input_df = pd.DataFrame({\n",
    "        'Feature': [\n",
    "            'Pregnancies', 'Glucose', 'Blood Pressure',\n",
    "            'Skin Thickness', 'Insulin', 'BMI',\n",
    "            'Diabetes Pedigree', 'Age'\n",
    "        ],\n",
    "        'Value': [\n",
    "            pregnancies, glucose, blood_pressure,\n",
    "            skin_thickness, insulin, bmi,\n",
    "            dpf, age\n",
    "        ]\n",
    "    })\n",
    "    st.table(input_df)\n",
    "    \n",
    "    if st.button('🔍 Predict Diabetes Risk', use_container_width=True):\n",
    "        prediction, probabilities = predict()\n",
    "        non_diabetic_prob = probabilities[0] * 100\n",
    "        diabetic_prob = probabilities[1] * 100\n",
    "        \n",
    "        st.subheader(\"Prediction Result\")\n",
    "        \n",
    "        if prediction == 1:\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class=\"result-box diabetic\">\n",
    "                <p class=\"big-font\">High Risk of Diabetes</p>\n",
    "                <p>Probability: {diabetic_prob:.2f}%</p>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "            st.warning(\"Consult a healthcare professional for further evaluation\")\n",
    "        else:\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class=\"result-box non-diabetic\">\n",
    "                <p class=\"big-font\">Low Risk of Diabetes</p>\n",
    "                <p>Probability: {non_diabetic_prob:.2f}%</p>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "            st.success(\"Maintain healthy lifestyle habits\")\n",
    "\n",
    "with col2:\n",
    "    st.header(\"Model Insights\")\n",
    "    \n",
    "    # Feature importance plot\n",
    "    st.subheader(\"Feature Importance\")\n",
    "    if hasattr(model, 'coef_'):\n",
    "        importance = pd.Series(np.abs(model.coef_[0]), \n",
    "                              index=input_df['Feature'])\n",
    "    else:  # Random Forest\n",
    "        importance = pd.Series(model.feature_importances_, \n",
    "                              index=input_df['Feature'])\n",
    "    \n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    importance.sort_values().plot(kind='barh', ax=ax, color='skyblue')\n",
    "    plt.title('Factors Influencing Diabetes Prediction')\n",
    "    plt.xlabel('Importance Score')\n",
    "    st.pyplot(fig)\n",
    "    \n",
    "    # Glucose vs BMI scatter plot\n",
    "    st.subheader(\"Glucose vs BMI Analysis\")\n",
    "    fig2 = plt.figure(figsize=(10, 6))\n",
    "\n",
    "    url = \"https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv\"\n",
    "    names = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', \n",
    "         'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']\n",
    "    sns.scatterplot(\n",
    "        x='Glucose', \n",
    "        y='BMI', \n",
    "        hue='Outcome', \n",
    "        data=pd.read_csv(url, names=names),\n",
    "        alpha=0.7\n",
    "    )\n",
    "    plt.axvline(x=glucose, color='r', linestyle='--')\n",
    "    plt.axhline(y=bmi, color='r', linestyle='--')\n",
    "    plt.title('Glucose vs BMI with Patient Position')\n",
    "    st.pyplot(fig2)\n",
    "\n",
    "# Footer\n",
    "st.markdown(\"---\")\n",
    "st.caption(\"Model trained on PIMA Indian Diabetes Dataset | Accuracy: 77-80%\")\n",
    "\n",
    "# Run with: streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78d4d717-c8d1-4ac1-87f6-0e66b4224a2e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
